In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')
df.head()

,RefId,Lemon?,Date Purchased,Auction,Vehicle Year,Vehicle Age,Make,Model,Trim,SubModel,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,26384,0,2/18/2009,MANHEIM,2002,7,DODGE,CARAVAN FWD V6 3.3L,Spo,MINIVAN 3.3L FFV SPORT,...,7968.0,9367.0,NaN,NaN,20928,32824,FL,3600.0,0,2063
1,20197,0,4/27/2010,OTHER,2005,5,FORD,FOCUS,ZX5,4D SEDAN ZX5,...,8971.0,9612.0,NaN,NaN,20234,95673,CA,5290.0,0,1243
2,46568,0,9/9/2009,MANHEIM,2004,5,CHEVROLET,IMPALA 3.4L V6 SFI,Bas,4D SEDAN,...,4432.0,5736.0,NaN,NaN,20928,33809,FL,5430.0,0,1703
3,36772,1,1/29/2010,MANHEIM,2004,6,NISSAN,FRONTIER PICKUP 2WD,XE,EXT CAB 3.3L XE,...,11353.0,13359.0,NaN,NaN,20207,75236,TX,6650.0,0,594
4,1931,0,10/19/2009,ADESA,2006,3,DODGE,CARAVAN GRAND FWD V6,SXT,MINIVAN 3.8L SXT,...,11910.0,14155.0,NaN,NaN,19638,33619,FL,7200.0,0,1623

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43789 entries, 0 to 43788
Data columns (total 34 columns):
RefId                                43789 non-null int64
Lemon?                               43789 non-null int64
Date Purchased                       43789 non-null object
Auction                              43789 non-null object
Vehicle Year                         43789 non-null int64
Vehicle Age                          43789 non-null int64
Make                                 43789 non-null object
Model                                43789 non-null object
Trim                                 42393 non-null object
SubModel                             43784 non-null object
Color                                43784 non-null object
Transmission                         43783 non-null object
WheelTypeID                          41907 non-null float64
WheelType                            41904 non-null object
VehOdo                               43789 non-null int64
Nationality                          43784 non-null object
Size                                 43784 non-null object
TopThreeAmericanName                 43784 non-null object
MMRAcquisitionAuctionAveragePrice    43775 non-null float64
MMRAcquisitionAuctionCleanPrice      43775 non-null float64
MMRAcquisitionRetailAveragePrice     43775 non-null float64
MMRAcquisitonRetailCleanPrice        43775 non-null float64
MMRCurrentAuctionAveragePrice        43598 non-null float64
MMRCurrentAuctionCleanPrice          43598 non-null float64
MMRCurrentRetailAveragePrice         43598 non-null float64
MMRCurrentRetailCleanPrice           43598 non-null float64
PRIMEUNIT                            2029 non-null object
AUCGUART                             2029 non-null object
BYRNO                                43789 non-null int64
VNZIP1                               43789 non-null int64
VNST                                 43789 non-null object
VehBCost                             43789 non-null float64
IsOnlineSale                         43789 non-null int64
WarrantyCost                         43789 non-null int64
dtypes: float64(10), int64(9), object(15)
memory usage: 11.4+ MB

In [4]:
#prediction is the result that needs to be predicted
#predictor is all the factor to do predictions
prediction = ['Lemon?']
predictor = list(df.drop(prediction, axis=1))
predictor

['RefId',
 'Date Purchased',
 'Auction',
 'Vehicle Year',
 'Vehicle Age',
 'Make',
 'Model',
 'Trim',
 'SubModel',
 'Color',
 'Transmission',
 'WheelTypeID',
 'WheelType',
 'VehOdo',
 'Nationality',
 'Size',
 'TopThreeAmericanName',
 'MMRAcquisitionAuctionAveragePrice',
 'MMRAcquisitionAuctionCleanPrice',
 'MMRAcquisitionRetailAveragePrice',
 'MMRAcquisitonRetailCleanPrice',
 'MMRCurrentAuctionAveragePrice',
 'MMRCurrentAuctionCleanPrice',
 'MMRCurrentRetailAveragePrice',
 'MMRCurrentRetailCleanPrice',
 'PRIMEUNIT',
 'AUCGUART',
 'BYRNO',
 'VNZIP1',
 'VNST',
 'VehBCost',
 'IsOnlineSale',
 'WarrantyCost']

# Categorical datas

## 1. Auction
## 2. Make
## 3. Trim
## 4. Color
## 5. Transmission
## 6. WheelTypeID = WheelType
####      drop WheelTypeID
## 7. Nationality
## 8. Size
## 9. TopThreeAmericanName
## 10. PRIMEUNIT
####       Yes/No >> Change yes to 1, No to -1, missing values to 0
## 11. AUCGUART
####      Green/Red, Green 1, Red -1, missng values 0
## 12. VNST

In [5]:
#Steps
#Drop Unuseful columns
#Columns to drop: WheelTypeID, RefID
#Fill in missing values
#One Hot Encode values

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''